/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import bd.conected;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author Brandon Llamas
 */
public class acompañamiento extends javax.swing.JFrame {
conected con=new conected ();
Connection cn=con.conect();
    /**
     * Creates new form acompañamiento
     */
    public acompañamiento() {
        initComponents();
    }
    public acompañamiento(int id,int ti,String nombre) throws SQLException{
    initComponents();
    if(id==0){
    txt_nombre.setText("Nombre estudiante: "+nombre);
    txt_tarjeta.setText("Tarjeta de identidad: "+Integer.toString(ti));
    }else{
    
        showdatosid(id);
    }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        txt_nombre = new javax.swing.JLabel();
        txt_tarjeta = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_seguimiento = new javax.swing.JTextPane();
        jt_fecha = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(528, 496));
        setSize(new java.awt.Dimension(528, 496));
        getContentPane().setLayout(null);

        txt_nombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_nombre.setText("Nombre estudiante");
        getContentPane().add(txt_nombre);
        txt_nombre.setBounds(20, 0, 193, 92);

        txt_tarjeta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_tarjeta.setText("Tarjeta de identidad");
        getContentPane().add(txt_tarjeta);
        txt_tarjeta.setBounds(280, 10, 210, 80);

        jLabel3.setText("fecha:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 100, 60, 14);

        jLabel4.setText("Seguimiento y apoyo realizado :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 160, 160, 14);

        jScrollPane1.setViewportView(jt_seguimiento);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 200, 440, 150);
        getContentPane().add(jt_fecha);
        jt_fecha.setBounds(80, 100, 110, 20);

        jMenu1.setText("File");

        jMenuItem1.setText("Guardar");
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("imagenes");
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("nuevo");
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(acompañamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(acompañamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(acompañamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(acompañamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new acompañamiento().setVisible(true);
            }
        });
    }
    private void showdatosid(int id) throws SQLException{
        Statement st= cn.createStatement();
        ResultSet rs=st.executeQuery("SELECT * FROM seguimiento where id="+id);
        while(rs.next()){
            txt_nombre.setText("Nombre estudiante:"+rs.getString("nombre_e"));
            jt_fecha.setText(rs.getString("fecha"));
            jt_seguimiento.setText(rs.getString("seguimiento_apoyo"));
            
        }
    
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jt_fecha;
    private javax.swing.JTextPane jt_seguimiento;
    private javax.swing.JLabel txt_nombre;
    private javax.swing.JLabel txt_tarjeta;
    // End of variables declaration//GEN-END:variables
}
